include .common.mk

SHELL := bash

.PHONY: all
all:
	+$(MAKE) -f verify.mk all

.PHONY: minimal
minimal:
	+$(MAKE) -f verify.mk minimal

.PHONY: verify
verify:
	+$(MAKE) -f verify.mk verify-all

.PHONY: prepare
prepare:
	+$(MAKE) -f verify.mk prepare

.PHONY: test
test:
	+$(MAKE) -f verify.mk test

.PHONY: accept
accept:
	+$(MAKE) -f verify.mk accept

.PHONY: extract-all
extract-all:
	+$(MAKE) -f verify.mk extract-all

.PHONY: echo-fstar
echo-fstar:
	+$(MAKE) -f verify.mk $@
.PHONY: echo-krml
echo-krml:
	+$(MAKE) -f verify.mk $@

.PHONY: ci
ci:
	+$(MAKE) -f verify.mk all test

.PHONY: depgraph
depgraph:
	+$(MAKE) -f verify.mk depgraph

.SUFFIXES:

.PHONY: watch
watch:
	while true; do \
		$(MAKE) ;\
		inotifywait -qre close_write .; \
	done

clean:
	rm -f .plugin.touch
	rm -rf obj/
	rm -rf inst/

clean-modules:
	git submodule foreach git clean -dXf

clean-full: clean clean-modules
	rm -f .*.touch

dist: extract-all
	rm -f dist/*.cu dist/*.h
	cp obj/*.cu obj/*.h dist
	@echo "Generated by Kuiper [https://github.com/FStarLang/kuiper]" > dist/BUILD_INFO
	@echo "Date: $$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> dist/BUILD_INFO
	@echo "Commit: $$(git rev-parse HEAD)" >> dist/BUILD_INFO
	@echo "F* commit: $$(git -C FStar rev-parse HEAD)" >> dist/BUILD_INFO
	@echo "Karamel commit: $$(git -C karamel rev-parse HEAD)" >> dist/BUILD_INFO

.PHONY: lint-c
lint-c:
	indent -linux -nut -i4 test/*.cu test/*.c.inc && rm -f test/*.cu~ test/*.c.inc~

.PHONY: lint-fstar
lint-fstar:
	./FStar/.scripts/remove_all_unused_opens.sh extraction
	./FStar/.scripts/remove_all_unused_opens.sh src
	( cd src && ../scripts/git-sed 's/[[:space:]]*$$//' )
	( cd extraction && ../scripts/git-sed 's/[[:space:]]*$$//' )
	( cd src && ../scripts/find-pulse-noix.sh )
	( cd src && ../scripts/check-attrs.sh )

.PHONY: lint
lint: lint-c lint-fstar

.PHONY: list-admits
list-admits:
	(git grep -n --color -w 'assume_\|assume\|admit\|tadmit\|magic' src; \
	find src -name \*.fsti | sort \
		| sed 's/i$$//;/Kuiper.Kernel.Base.fst/d;/Kuiper.Base.fst/d;/Kuiper.\(Ref\|Array\|Array.Vectorized\|AtomicOps\).fst/d;/Kuiper.TensorCore.Base.fst/d;/Kuiper.\(Float[0-9]\+\|SizeT\).fst/d' \
		| while read fn; do if [[ ! -f $$fn ]]; then echo Missing implementation file: $$fn; fi; done \
	) | less -R

.PHONY: wc
wc:
	echo All F*:
	find src/ \( -name '*.fst' -o -name '*.fsti' \) -exec cat {} \+ | grep '[^ ]' | wc -l
	echo CUDA:
	find dist/ -name '*.cu' -exec cat {} \+ | grep '[^ ]' | wc -l
	echo Examples only:
	find src/examples/ \( -name '*.fst' -o -name '*.fsti' \) -exec cat {} \+ | grep '[^ ]' | wc -l
	echo GEMMs in polymorphic form:
	find src/lib/poly/gemm \( -name '*.fst' -o -name '*.fsti' \) -exec cat {} \+ | grep '[^ ]' | wc -l
	echo Data views:
	find src/lib/data \( -name '*.fst' -o -name '*.fsti' \) -exec cat {} \+ | grep '[^ ]' | wc -l

.PHONY: src-package
src-package: kuiper-src.tar.gz

.PHONY: kuiper-src.tar.gz
kuiper-src.tar.gz:
	# Relying on Git here. This will NOT place uncommited
	# changes in the archive. And sadly one cannot run this
	# rule from an extracted archive.
	rm -f $@
	git archive HEAD -o kuiper-src.tar
	# Archive submodules and concatenate them
	git -C FStar   archive --prefix=FStar/   HEAD -o ../fstar.tar
	git -C karamel archive --prefix=karamel/ HEAD -o ../karamel.tar
	tar --concatenate --file=kuiper-src.tar fstar.tar
	tar --concatenate --file=kuiper-src.tar karamel.tar
	gzip kuiper-src.tar
	rm -f fstar.tar karamel.tar kuiper-src.tar

# "bench package" is also a "test package"
.PHONY: bench-package
bench-package: kuiper-bench.tar.gz

kuiper-bench.tar.gz: verify extract-all
	rm -rf kuiper-bench
	mkdir -p kuiper-bench
	mkdir -p kuiper-bench/obj
	cp -r obj/*.cu obj/*.h kuiper-bench/obj
	cp -r include kuiper-bench/include
	cp -r test kuiper-bench/test
	cp -r scripts kuiper-bench/scripts
	cp -r configure kuiper-bench/configure
	cp -r bench-package.mk kuiper-bench/Makefile
	cp -r nvcc.mk kuiper-bench/nvcc.mk
	cp -r .common.mk kuiper-bench/.common.mk
	cp -r .configure.mk kuiper-bench/.configure.mk
	cp -r bench kuiper-bench/bench
	rm -f kuiper-bench/bench/*.o   # clean built files
	rm -f kuiper-bench/bench/bench # clean built files
	tar czf kuiper-bench.tar.gz ./kuiper-bench
	rm -rf ./kuiper-bench

.PHONY: test-bench-package
test-bench-package: bench-package
	rm -rf _tmp
	mkdir _tmp
	cd _tmp && tar xzf ../kuiper-bench.tar.gz
	$(MAKE) -C _tmp
	rm -rf _tmp
