#!/bin/bash

cat << EOF
module Kuiper.GEMM.TensorCore2D
#lang-pulse

// THIS FILE IS AUTOMATICALLY GENERATED BY A SCRIPT, DO NOT EDIT

open Kuiper
open Kuiper.Array.Vectorized { has_vec_cpy, chunk }
open Kuiper.GEMM.TensorCore2D.Inst { spec }

// Dynamic parameter version for shmem size
let g_gemm_f16_f16_16x16x16_2x2 bm bn bk =
  admit();
  spec half half bm bn bk 16sz 16sz 16sz 2sz 2sz

let g_gemm_f16_f16_16x16x16_4x4 bm bn bk =
  admit();
  spec half half bm bn bk 16sz 16sz 16sz 4sz 4sz

let g_gemm_f16_f16_16x16x16_8x8 bm bn bk =
  admit();
  spec half half bm bn bk 16sz 16sz 16sz 8sz 8sz

EOF

for bm in 32 64 128; do
  if [ $((bm % 16)) -ne 0 ]; then continue; fi # tc tile
  for bn in 32 64 128; do
    if [ $((bn % 8)) -ne 0 ]; then continue; fi # chunk
    if [ $((bn % 16)) -ne 0 ]; then continue; fi # tc tile
    for bk in 8 16 32 64; do
      if [ $((bk % 8)) -ne 0 ]; then continue; fi # chunk
      if [ $((bk % 16)) -ne 0 ]; then continue; fi # tc tile
      if [ $(((2 * bm * bk) + (2 * bk * bn))) -gt 49152 ]; then continue; fi # shmem size constraint
      for wm in 2 4 8 16; do
        if [ $((bm % (16 * wm))) -ne 0 ]; then continue; fi
        for wn in 2 4 8 16; do
          if [ $((bn % (16 * wn))) -ne 0 ]; then continue; fi
          if [ $(((bm / (wm*16)) * (bn / (wn*16)) * 32)) -gt 1024 ]; then continue; fi
          echo "let g_gemm_f16_f16_${bm}x${bn}x${bk}_16x16x16_${wm}x${wn} = spec half half ${bm}sz ${bn}sz ${bk}sz 16sz 16sz 16sz ${wm}sz ${wn}sz"
        done
      done
    done
  done
done
