#!/usr/bin/env bash
# Updates dist/ from obj/ and regenerates BUILD_INFO only when
# the generated .cu/.h files have actually changed.

set -euo pipefail

changed=0

for f in obj/*.cu obj/*.h; do
    base=$(basename "$f")
    dst="dist/$base"
    if [[ ! -f "$dst" ]] || ! cmp -s "$f" "$dst"; then
        changed=1
        break
    fi
done

# Also check for files removed from obj/ but still present in dist/
for f in dist/*.cu dist/*.h; do
    [[ -e "$f" ]] || continue
    base=$(basename "$f")
    if [[ ! -f "obj/$base" ]]; then
        changed=1
        break
    fi
done

if [[ "$changed" -eq 0 ]]; then
    echo "dist/ is up to date."
    exit 0
fi

rm -f dist/*.cu dist/*.h
cp obj/*.cu obj/*.h dist

cat > dist/BUILD_INFO <<EOF
Generated by Kuiper [https://github.com/FStarLang/kuiper]
Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
Commit: $(git rev-parse HEAD)
F* commit: $(git -C FStar rev-parse HEAD)
Karamel commit: $(git -C karamel rev-parse HEAD)
EOF

echo "dist/ updated."
