name: Test build

on:
  push:
    branches-ignore:
    - _**
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        description: Enable debug output
        type: boolean
        default: false
      nocache:
        description: Do not use stored cache
        type: boolean
        default: false

jobs:
  build:
    # NB: we need the runner to have a working CUDA setup (toolkit + driver)
    runs-on: [self-hosted, linux, X64, cuda]
    container:
      image: mtzguido/pulse-cuda-devcontainer
      options: --gpus all
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          sudo apt-get update && sudo apt-get install -y jq
          whoami
          id
          env

      - run: find . -delete
      - name: Check out repo
        uses: actions/checkout@v4

      # Fixup HOME (https://github.com/actions/runner/issues/863)
      - name: Setup HOME
        run: |
          echo "HOME=/home/vscode" >> $GITHUB_ENV
          echo "PATH=/usr/local/bin/:$PATH" >> $GITHUB_ENV

      # FIXME: env or path gets broken
      # - uses: mtzguido/set-opam-env@master

      # If these fail, stop right now.
      - run: which z3-4.8.5

      - name: Get submodules
        run: |
          git submodule init
          git submodule update

      - name: Check CUDA
        run: ./scripts/check-cuda.sh

      - name: Startup check
        run: |
          mkdir -p out
          nvcc -I include/ -o out/startup.exe test/startup.cu
          ./out/startup.exe

      - name: Set debug mode
        if: ${{ inputs.debug }}
        run: |
          echo "V=1" >>$GITHUB_ENV
          echo "OTHERFLAGS=-d" >>$GITHUB_ENV

      - name: read F* commit
        id: fstarcommit
        run: |
          cd FStar
          C=$(git rev-parse HEAD)
          echo "FSTARCOMMIT=$C" >>"$GITHUB_OUTPUT"

      - name: Try fetch cached F*
        id: fstarcache
        if: ${{ inputs.nocache != 'true' && github.event_name != 'schedule' }}
        uses: actions/cache/restore@v4
        with:
          path: inst
          key: fstar-${{ runner.os }}-${{ runner.arch }}-${{steps.fstarcommit.outputs.FSTARCOMMIT}}

      - name: Fake touchfile
        if: ${{ steps.fstarcache.outputs.cache-hit = 'true' }}
        run: touch .fstar.touch

      - name: Build F*
        if: ${{ steps.fstarcache.outputs.cache-hit != 'true' }}
        run: |
          eval $(opam env)
          make -j$(nproc) -f verify.mk .fstar.touch

      - name: Save F*
        uses: actions/cache/save@v4
        if: ${{ steps.fstarcache.outputs.cache-hit != 'true' }}
        with:
          path: inst
          key: fstar-${{ runner.os }}-${{ runner.arch }}-${{steps.fstarcommit.outputs.FSTARCOMMIT}}

      - name: Run CI Makefile rule
        run: |
          eval $(opam env)
          make -kj$(nproc) -Otarget ci |& tee LOG

      - name: Make artifact with output
        if: ${{ always () }}
        continue-on-error: true
        uses: actions/upload-artifact@master
        with:
          name: output
          path: out/

      - name: Spit out all CUDA files into action log
        if: ${{ always () }}
        run: |
          for i in out/*.cu; do
            echo "::group::$i"
            cat "$i"
            echo "::endgroup::"
          done || true

      - name: Make artifact with failed state
        if: ${{ always () && inputs.debug }}
        uses: actions/upload-artifact@master
        continue-on-error: true
        with:
          name: all
          include-hidden-files: true
          path: '**'
