name: Test build

on:
  push:
    branches-ignore:
    - _**
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # NB: we need the runner to have a working CUDA setup (toolkit + driver)
    runs-on: [self-hosted, linux, X64, cuda]
    container:
      image: mtzguido/pulse-cuda-devcontainer
      options: --gpus all
    defaults:
      run:
        # Setting the default shell to bash. This is not only more standard,
        # but also makes sure that we run with -o pipefail, so we can safely
        # pipe data (such as | tee LOG) without missing out on failures
        # and getting false positives. If you want to change the default shell,
        # keep in mind you need a way to handle this.
        shell: bash
    steps:
      - run: |
          whoami
          id
          env

      - run: find . -delete
      - name: Check out repo
        uses: actions/checkout@v4

      # Fixup HOME (https://github.com/actions/runner/issues/863)
      - name: Setup HOME
        run: |
          echo "HOME=/home/vscode" >> $GITHUB_ENV
          echo "PATH=/usr/local/bin/:$PATH" >> $GITHUB_ENV

      # FIXME: env or path gets broken
      # - uses: mtzguido/set-opam-env@master

      # If these fail, stop right now.
      - run: which z3-4.8.5

      - name: Get submodules
        run: |
          git submodule init
          git submodule update

      - name: Check CUDA
        run: ./scripts/check-cuda.sh

      - name: Startup check
        run: |
          nvcc -I include/ -o out/startup.exe test/startup.cu
          ./out/startup.exe

      - name: Run CI Makefile rule
        run: |
          eval $(opam env)
          make -skj$(nproc) -Otarget ci

      - name: Run CI Makefile rule
        run: |
          eval $(opam env)
          make -skj$(nproc) -Otarget ci

      - name: Make artifact with output
        if: ${{ always () }}
        uses: actions/upload-artifact@master
        with:
          name: output
          path: out/

      - name: Spit out all CUDA files into action log
        if: ${{ always () }}
        run: |
          for i in out/*.cu; do
            echo "::group::$i"
            cat "$i"
            echo "::endgroup::"
          done
