#!/bin/bash

cat << EOF
module Klas.GEMM.TensorCore2D.To
#lang-pulse

// THIS FILE IS AUTOMATICALLY GENERATED BY A SCRIPT, DO NOT EDIT

open Kuiper
open Kuiper.Array.Vectorized { has_vec_cpy, chunk }
open Klas.GEMM.TensorCore2D.To.Inst { spec }

EOF

# Tweak these lists to control which instances are generated.
all_tm="16"
all_tn="16"
all_tk="16"
all_bm="64 128"
all_bn="64 128"
all_bk="16 32 64"
all_wm="2 4 8 16"
all_wn="2 4 8 16"

chunk=8       # 8 bf16s = 16 bytes
et_ab_size=2  # bf16
et_acc_size=4 # f32

for tm in $all_tm; do
  for tn in $all_tn; do
    for tk in $all_tk; do
      for bm in $all_bm; do
        if [ $((bm % tm)) -ne 0 ]; then continue; fi
        for bn in $all_bn; do
          if [ $((bn % chunk)) -ne 0 ]; then continue; fi
          if [ $((bn % tn)) -ne 0 ]; then continue; fi
          for bk in $all_bk; do
            if [ $((bk % chunk)) -ne 0 ]; then continue; fi
            if [ $((bk % tk)) -ne 0 ]; then continue; fi
            for wm in $all_wm; do
              if [ $((bm % (tm * wm))) -ne 0 ]; then continue; fi
              for wn in $all_wn; do
                if [ $((bn % (tn * wn))) -ne 0 ]; then continue; fi

                warps=$((bm / (wm * tm) * (bn / (wn * tn))))
                threads=$((warps * 32))
                shmem_bytes=$((et_ab_size * (bm * bk + bk * bn) + et_acc_size * warps * tm * tn))

                if [ $threads -gt 1024 ]; then continue; fi
                if [ $shmem_bytes -gt 101376 ]; then continue; fi
                if [ $(((bm * bk) % (chunk * threads))) -ne 0 ]; then continue; fi
                if [ $(((bk * bn) % (chunk * threads))) -ne 0 ]; then continue; fi

                echo "let g_gemm_bf16_f32_bf16_${bm}x${bn}x${bk}_${tm}x${tn}x${tk}_${wm}x${wn} = spec bf16 f32 bf16 ${bm}sz ${bn}sz ${bk}sz ${tm}sz ${tn}sz ${tk}sz ${wm}sz ${wn}sz"
              done
            done
          done
        done
      done
    done
  done
done

